scss_files: 'src/sass/**/*.scss'

linters:

  BorderZero:
    enabled: true
    convention: none

  BemDepth:
    enabled: true

  Comment:
    exclude:
      - 'src/sass/_functions.scss'
      - 'src/sass/_meta.scss'

  DeclarationOrder:
    enabled: false

  Indentation:
    width: 2

  LeadingZero:
    enabled: false

  NameFormat:
    exclude:
      - 'src/sass/_widgets.scss'

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes
